config/routes.rb
Wandrr::Application.routes.draw do

  devise_for :users

  resources :activities #, only: :index

  resources :destinations, only: :index do
    resources :activities
  end

  resources :trips do
    resources :destinations
  end

  root :to => 'trips#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :description, :name, :date, :addresse

  belongs_to :destination

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  attr_accessible :description, :name

  belongs_to :trip
  has_many :activities, :dependent => :destroy

  validates_presence_of :name

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :destinations, :dependent => :destroy

  validates_presence_of :name

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @destination = Destination.find(params[:destination_id])
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @destination = Destination.find(params[:destination_id])
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @destination = Destination.find(params[:destination_id])
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @destination = Destination.find(params[:destination_id])
    @activity = @destination.activities.new(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to destination_activity_path(@destination, @activity), notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @destination = Destination.find(params[:id])
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to destination_activity_path(@destination, @activity), notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @destinations }
    end
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
    @trip = Trip.find(params[:trip_id])
    @destination = Destination.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @destination }
    end
  end

  # GET /destinations/new
  # GET /destinations/new.json
  def new
    @trip = Trip.find(params[:trip_id])
    @destination = Destination.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @destination }
    end
  end

  # GET /destinations/1/edit
  def edit
    @trip = Trip.find(params[:trip_id])
    @destination = Destination.find(params[:id])
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @trip = Trip.find(params[:trip_id])
    @destination = @trip.destinations.new(params[:destination])

    respond_to do |format|
      if @destination.save
        format.html { redirect_to trip_destination_path(@trip, @destination), notice: 'Destination was successfully created.' }
        format.json { render json: @destination, status: :created, location: @destination }
      else
        format.html { render action: "new" }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /destinations/1
  # PUT /destinations/1.json
  def update
    @destination = Destination.find(params[:id])
    @trip = @destination.trip

    respond_to do |format|
      if @destination.update_attributes(params[:destination])
        format.html { redirect_to trip_destination_path(@destination.trip, @destination), notice: 'Destination was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination = Destination.find(params[:id])
    @destination.destroy

    respond_to do |format|
      format.html { redirect_to destinations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/activities/_form.html.erb
<%= form_for [@destination, @activity] do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :addresse %><br />
    <%= f.text_field :addresse %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', destination_activity_path(@destination, @activity) %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Addresse</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.name %></td>
    <td><%= activity.date %></td>
    <td><%= activity.addresse %></td>
    <td><%= activity.description %></td>
    <td><%= link_to 'Show', destination_activity_path(activity.destination.id, activity.id) %></td>
    <td><%= link_to 'Edit', edit_destination_activity_path(activity.destination.id, activity.id) %></td>
    <td><%= link_to 'Destroy', destination_activity_path(activity.destination.id, activity.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @activity.name %>
</p>

<p>
  <b>Date:</b>
  <%= @activity.date %>
</p>

<p>
  <b>Addresse:</b>
  <%= @activity.addresse %>
</p>

<p>
  <b>Description:</b>
  <%= @activity.description %>
</p>

<%= link_to 'Edit', edit_destination_activity_path(@destination, @activity) %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/_form.html.erb
<%= form_for [@trip, @destination] do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing destination</h1>

<%= render 'form' %>

<%= link_to 'Show', trip_destination_path(@trip, @destination) %> |
<%= link_to 'Back', trip_path %>

app/views/destinations/index.html.erb
<h1>Listing destinations</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Trip</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @destinations.each do |destination| %>
  <tr>
    <td><%= destination.name %></td>
    <td><%= destination.trip.name %></td>
    <td><%= destination.description %></td>
    <td><%= link_to 'Show', trip_destination_path(destination.trip.id, destination.id) %></td>
    <td><%= link_to 'Edit', edit_trip_destination_path(destination.trip.id, destination.id) %></td>
    <td><%= link_to 'Destroy', trip_destination_path(destination.trip.id, destination.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/destinations/new.html.erb
<h1>New destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @destination.name %>
</p>

<p>
  <b>Description:</b>
  <%= @destination.description %>
</p>

<table>
	<tr>
		<th>Activity</th>
		<th>Date</th>
		<th>Addresse</th>
		<th>Description</th>
	</tr>
	<% @destination.activities.each do |activity| %>
	<tr>
		<td><%= link_to activity.name, destination_activity_path(@trip, activity) %></td>
		<td><%= activity.date %></td>
		<td><%= activity.addresse %></td>
		<td><%= activity.description %></td>
	</tr>
	<% end %>
</table>

<p>
  <%= link_to 'New Activity', new_destination_activity_path(@destination) %>
</p>

<%= link_to 'Edit', edit_trip_destination_path(@trip, @destination) %> |
<%= link_to 'Back', trip_path(@trip) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wandrr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render :partial => 'shared/nav' %>

<%= yield %>

</body>
</html>

app/views/shared/_nav.html.erb
<nav>
	<ul>
		<li><a href="/">Home</a></li>
		<li><%= link_to "Trips", trips_path %></li>
		<li><%= link_to "Destinations", destinations_path %></li>
		<li><%= link_to "Activities", activities_path %></li>
	</ul>

	<ul>
	<% if user_signed_in? %>
		<li><%= link_to current_user.email, edit_user_registration_path %></li>
		<li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
	<% else %>
		<li><%= link_to "Sign Up", new_user_registration_path %></li>
		<li><%= link_to "Log In", new_user_session_path %></li>
	<% end %>
	</ul>
</nav>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>Listing trips</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trips.each do |trip| %>
  <tr>
    <td><%= trip.name %></td>
    <td><%= trip.description %></td>
    <td><%= link_to 'Show', trip %></td>
    <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
    <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @trip.name %>
</p>

<p>
  <b>Description:</b>
  <%= @trip.description %>
</p>




<table>
	<tr>
		<th>Destination</th>
		<th>Description</th>
	</tr>
	<% @trip.destinations.each do |destination| %>
	<tr>
		<td><%= link_to destination.name, trip_destination_path(@trip, destination) %></td>
		<td><%= destination.description %></td>
	</tr>
	<% end %>
</table>

<p>
  <%= link_to 'New Destination', new_trip_destination_path(@trip) %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>